import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Plus, Search, Edit, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { formatCurrency } from "@/lib/payroll-utils";
import { useAuth } from "@/hooks/useAuth";

interface Employee {
  id: string;
  employee_code: string;
  first_name: string;
  last_name: string;
  middle_name: string | null;
  email: string | null;
  phone: string | null;
  department: string | null;
  job_title: string | null;
  basic_salary: number;
  hire_date: string;
  employment_status: string;
  sss_number: string | null;
  philhealth_number: string | null;
  pagibig_number: string | null;
  tin_number: string | null;
}

const emptyForm = {
  first_name: "", last_name: "", middle_name: "", email: "", phone: "",
  department: "", job_title: "", basic_salary: 0, hire_date: new Date().toISOString().split("T")[0],
  sss_number: "", philhealth_number: "", pagibig_number: "", tin_number: "",
};

export default function Employees() {
  const { isAdminOrHR } = useAuth();
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<Employee | null>(null);
  const [form, setForm] = useState(emptyForm);

  const fetchEmployees = async () => {
    const { data, error } = await supabase.from("employees").select("*").order("created_at", { ascending: false });
    if (error) { toast.error(error.message); return; }
    setEmployees(data || []);
    setLoading(false);
  };

  useEffect(() => { fetchEmployees(); }, []);

  const handleSave = async () => {
    try {
      if (editing) {
        const { error } = await supabase.from("employees").update({
          first_name: form.first_name, last_name: form.last_name, middle_name: form.middle_name || null,
          email: form.email || null, phone: form.phone || null, department: form.department || null,
          job_title: form.job_title || null, basic_salary: form.basic_salary, hire_date: form.hire_date,
          sss_number: form.sss_number || null, philhealth_number: form.philhealth_number || null,
          pagibig_number: form.pagibig_number || null, tin_number: form.tin_number || null,
        }).eq("id", editing.id);
        if (error) throw error;
        toast.success("Employee updated");
      } else {
        const { error } = await supabase.from("employees").insert({
          employee_code: "", // auto-generated by trigger
          first_name: form.first_name, last_name: form.last_name, middle_name: form.middle_name || null,
          email: form.email || null, phone: form.phone || null, department: form.department || null,
          job_title: form.job_title || null, basic_salary: form.basic_salary, hire_date: form.hire_date,
          sss_number: form.sss_number || null, philhealth_number: form.philhealth_number || null,
          pagibig_number: form.pagibig_number || null, tin_number: form.tin_number || null,
        });
        if (error) throw error;
        toast.success("Employee added");
      }
      setDialogOpen(false);
      setEditing(null);
      setForm(emptyForm);
      fetchEmployees();
    } catch (err: any) {
      toast.error(err.message);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this employee?")) return;
    const { error } = await supabase.from("employees").delete().eq("id", id);
    if (error) toast.error(error.message);
    else { toast.success("Employee deleted"); fetchEmployees(); }
  };

  const openEdit = (emp: Employee) => {
    setEditing(emp);
    setForm({
      first_name: emp.first_name, last_name: emp.last_name, middle_name: emp.middle_name || "",
      email: emp.email || "", phone: emp.phone || "", department: emp.department || "",
      job_title: emp.job_title || "", basic_salary: emp.basic_salary, hire_date: emp.hire_date,
      sss_number: emp.sss_number || "", philhealth_number: emp.philhealth_number || "",
      pagibig_number: emp.pagibig_number || "", tin_number: emp.tin_number || "",
    });
    setDialogOpen(true);
  };

  const filtered = employees.filter(e =>
    `${e.first_name} ${e.last_name} ${e.employee_code} ${e.department}`.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div>
      <div className="page-header flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="page-title">Employees</h1>
          <p className="page-description">{employees.length} total employees</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input placeholder="Search employees..." value={search} onChange={e => setSearch(e.target.value)} className="pl-9 w-64" />
          </div>
          {isAdminOrHR() && (
            <Dialog open={dialogOpen} onOpenChange={(o) => { setDialogOpen(o); if (!o) { setEditing(null); setForm(emptyForm); } }}>
              <DialogTrigger asChild>
                <Button><Plus className="w-4 h-4 mr-2" />Add Employee</Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>{editing ? "Edit Employee" : "Add New Employee"}</DialogTitle>
                </DialogHeader>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                  <div className="space-y-2">
                    <Label>First Name *</Label>
                    <Input value={form.first_name} onChange={e => setForm({ ...form, first_name: e.target.value })} required />
                  </div>
                  <div className="space-y-2">
                    <Label>Last Name *</Label>
                    <Input value={form.last_name} onChange={e => setForm({ ...form, last_name: e.target.value })} required />
                  </div>
                  <div className="space-y-2">
                    <Label>Middle Name</Label>
                    <Input value={form.middle_name} onChange={e => setForm({ ...form, middle_name: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Email</Label>
                    <Input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Phone</Label>
                    <Input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Department</Label>
                    <Input value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Job Title</Label>
                    <Input value={form.job_title} onChange={e => setForm({ ...form, job_title: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Basic Salary (₱) *</Label>
                    <Input type="number" value={form.basic_salary} onChange={e => setForm({ ...form, basic_salary: parseFloat(e.target.value) || 0 })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Hire Date *</Label>
                    <Input type="date" value={form.hire_date} onChange={e => setForm({ ...form, hire_date: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>SSS Number</Label>
                    <Input value={form.sss_number} onChange={e => setForm({ ...form, sss_number: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>PhilHealth Number</Label>
                    <Input value={form.philhealth_number} onChange={e => setForm({ ...form, philhealth_number: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>Pag-IBIG Number</Label>
                    <Input value={form.pagibig_number} onChange={e => setForm({ ...form, pagibig_number: e.target.value })} />
                  </div>
                  <div className="space-y-2">
                    <Label>TIN Number</Label>
                    <Input value={form.tin_number} onChange={e => setForm({ ...form, tin_number: e.target.value })} />
                  </div>
                </div>
                <div className="flex justify-end gap-3 mt-6">
                  <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
                  <Button onClick={handleSave} disabled={!form.first_name || !form.last_name}>Save</Button>
                </div>
              </DialogContent>
            </Dialog>
          )}
        </div>
      </div>

      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Code</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Department</TableHead>
              <TableHead>Position</TableHead>
              <TableHead>Salary</TableHead>
              <TableHead>Status</TableHead>
              {isAdminOrHR() && <TableHead className="w-20">Actions</TableHead>}
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow><TableCell colSpan={7} className="text-center py-12 text-muted-foreground">Loading...</TableCell></TableRow>
            ) : filtered.length === 0 ? (
              <TableRow><TableCell colSpan={7} className="text-center py-12 text-muted-foreground">No employees found</TableCell></TableRow>
            ) : (
              filtered.map(emp => (
                <TableRow key={emp.id}>
                  <TableCell className="font-mono text-sm">{emp.employee_code}</TableCell>
                  <TableCell className="font-medium">{emp.first_name} {emp.last_name}</TableCell>
                  <TableCell>{emp.department || "—"}</TableCell>
                  <TableCell>{emp.job_title || "—"}</TableCell>
                  <TableCell>{formatCurrency(emp.basic_salary)}</TableCell>
                  <TableCell>
                    <Badge variant={emp.employment_status === "active" ? "default" : "secondary"}>
                      {emp.employment_status}
                    </Badge>
                  </TableCell>
                  {isAdminOrHR() && (
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <Button variant="ghost" size="icon" onClick={() => openEdit(emp)}><Edit className="w-4 h-4" /></Button>
                        <Button variant="ghost" size="icon" onClick={() => handleDelete(emp.id)}><Trash2 className="w-4 h-4 text-destructive" /></Button>
                      </div>
                    </TableCell>
                  )}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
